run:
  name: mace_A_r6_l3_h128
  output_root: outputs/mace

data:
  train_path: ../dataset/train.extxyz
  valid_path: ../dataset/valid.extxyz
  test_path: ../dataset/test.extxyz
  energy_key: energy
  forces_key: forces
  stress_key: stress

model:
  model_type: MACE
  r_max: 6.0
  num_interactions: 3
  hidden_irreps: "128x0e + 128x1o"

training:
  seed: 42
  device: cuda
  default_dtype: float32
  batch_size: 8
  valid_batch_size: 8
  max_epochs: 200
  lr: 0.001
  weight_decay: 5.0e-7
  scheduler: ReduceLROnPlateau
  energy_weight: 1.0
  forces_weight: 100.0
  stress_weight: 1.0
  ema: true
  ema_decay: 0.99
  patience: 20
