run:
  output_root: outputs/mace
  name: mace_C_r7p6_l3_h128
data:
  train_path: dataset/train_split.extxyz
  valid_path: dataset/valid_split.extxyz
  test_path: dataset/test.extxyz
  energy_key: energy
  forces_key: forces
  stress_key: stress
training:
  seed: 42
  device: cuda
  default_dtype: float32
  valid_batch_size: 6
  weight_decay: 1e-08
  scheduler: ReduceLROnPlateau
  energy_weight: 1.0
  forces_weight: 100.0
  stress_weight: 1.0
  ema: true
  ema_decay: 0.99
  patience: 20
  extra_args:
    - "--eval_interval"
    - 1
  batch_size: 6
  max_epochs: 250
  lr: 0.0003
model:
  model_type: MACE
  r_max: 7.6
  num_interactions: 3
  hidden_irreps: 128x0e + 128x1o
